GET http://localhost:4000/api/getallusers

###
post http://localhost:4000/api/signup
Content-Type: application/json

{
    "fullName": "Dawit", 
    "username": "d", 
    "email": "d", "password": "d", 
    "confirmPassword": "d", 
    "role":"null"
}
###
{
    "password":"p",
    "email":"e",
    "username":"username",
    "confirmPassword":"p",
    "fullName":"fullName",
    "role":"user"
}

###
post http://localhost:4000/api/login
Content-Type: application/json

{
    "email":"d",
    "password":"d"
} 

###
###
put http://localhost:4000/api/updateprofile/61311133e9b83a45912b842f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdXJyZW50VXNlciI6eyJfaWQiOiI2MTMxMTEzM2U5YjgzYTQ1OTEyYjg0MmYiLCJmdWxsTmFtZSI6ImZ1bGxOYW1lIiwiZW1haWwiOiJlIiwidXNlcm5hbWUiOiJ1c2VybmFtZSIsInBhc3N3b3JkIjoiJDJhJDEyJE1ySFd2OFJMakR0U3FUczguRWp0V2V3VkVTS0JtakhUSVAzaXFPUjhzTWNiQVh1NXU5Z2ZhIiwicm9sZSI6InVzZXIiLCJfX3YiOjB9LCJpYXQiOjE2MzA2MDU2NzEsImV4cCI6MTYzMDYwNzQ3MX0.U4JLOP2t-jjHh6vwguMwbjKfTV54Hg-LBypt02Zm4fo
Content-Type: application/json

{
    "email":"soliana@gmail.com"
}  
###
delete http://localhost:4000/api/deleteprofile/61311133e9b83a45912b842f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdXJyZW50VXNlciI6eyJfaWQiOiI2MTMxMTEzM2U5YjgzYTQ1OTEyYjg0MmYiLCJmdWxsTmFtZSI6ImZ1bGxOYW1lIiwiZW1haWwiOiJlIiwidXNlcm5hbWUiOiJ1c2VybmFtZSIsInBhc3N3b3JkIjoiJDJhJDEyJE1ySFd2OFJMakR0U3FUczguRWp0V2V3VkVTS0JtakhUSVAzaXFPUjhzTWNiQVh1NXU5Z2ZhIiwicm9sZSI6InVzZXIiLCJfX3YiOjB9LCJpYXQiOjE2MzA2MDU2NzEsImV4cCI6MTYzMDYwNzQ3MX0.U4JLOP2t-jjHh6vwguMwbjKfTV54Hg-LBypt02Zm4fo
###
get http://localhost:4000/api/getallcomplaints